apiVersion: v1
kind: Service
metadata:
  name: app-order-database-postgres-service
spec:
  selector:
    app: app-order-database-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP