name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    outputs:
      jar-path: ${{ steps.package.outputs.jar-path }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build e Testes Maven
        run: mvn -B clean verify

      - name: Package JAR
        id: package
        run: |
          mvn -B package -DskipTests
          echo "jar-path=target/*.jar" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: SonarCloud Analysis
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=LucasMachadoID2_tech-challenge-fiap-order \
            -Dsonar.organization=lucasmachadoid2 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}